// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type MindmapEdge struct {
	ID     string `json:"id"`
	Source string `json:"source"`
	Target string `json:"target"`
	Kind   string `json:"kind"`
	Volume int32  `json:"volume"`
}

type MindmapNode struct {
	ID               string  `json:"id"`
	Type             string  `json:"type"`
	Subtype          *string `json:"subtype"`
	Label            string  `json:"label"`
	Description      *string `json:"description"`
	PrimaryAttribute *string `json:"primaryAttribute"`
}
