// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const createEdge = `-- name: CreateEdge :one
INSERT INTO edges (id, source, target, kind, volume)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, source, target, kind, volume
`

type CreateEdgeParams struct {
	ID     string `json:"id"`
	Source string `json:"source"`
	Target string `json:"target"`
	Kind   string `json:"kind"`
	Volume int32  `json:"volume"`
}

func (q *Queries) CreateEdge(ctx context.Context, arg CreateEdgeParams) (Edge, error) {
	row := q.db.QueryRow(ctx, createEdge,
		arg.ID,
		arg.Source,
		arg.Target,
		arg.Kind,
		arg.Volume,
	)
	var i Edge
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.Target,
		&i.Kind,
		&i.Volume,
	)
	return i, err
}

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (id, type, subtype, label, description, schedule)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, type, subtype, label, description, schedule
`

type CreateNodeParams struct {
	ID          string  `json:"id"`
	Type        string  `json:"type"`
	Subtype     *string `json:"subtype"`
	Label       string  `json:"label"`
	Description *string `json:"description"`
	Schedule    *string `json:"schedule"`
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, createNode,
		arg.ID,
		arg.Type,
		arg.Subtype,
		arg.Label,
		arg.Description,
		arg.Schedule,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Subtype,
		&i.Label,
		&i.Description,
		&i.Schedule,
	)
	return i, err
}

const deleteEdge = `-- name: DeleteEdge :exec
DELETE FROM edges WHERE id = $1
`

func (q *Queries) DeleteEdge(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteEdge, id)
	return err
}

const deleteNode = `-- name: DeleteNode :exec
DELETE FROM nodes WHERE id = $1
`

func (q *Queries) DeleteNode(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteNode, id)
	return err
}

const getEdge = `-- name: GetEdge :one
SELECT id, source, target, kind, volume FROM edges WHERE id = $1
`

func (q *Queries) GetEdge(ctx context.Context, id string) (Edge, error) {
	row := q.db.QueryRow(ctx, getEdge, id)
	var i Edge
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.Target,
		&i.Kind,
		&i.Volume,
	)
	return i, err
}

const getNode = `-- name: GetNode :one
SELECT id, type, subtype, label, description, schedule FROM nodes WHERE id = $1
`

func (q *Queries) GetNode(ctx context.Context, id string) (Node, error) {
	row := q.db.QueryRow(ctx, getNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Subtype,
		&i.Label,
		&i.Description,
		&i.Schedule,
	)
	return i, err
}

const listEdges = `-- name: ListEdges :many
SELECT id, source, target, kind, volume FROM edges ORDER BY id
`

func (q *Queries) ListEdges(ctx context.Context) ([]Edge, error) {
	rows, err := q.db.Query(ctx, listEdges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Edge
	for rows.Next() {
		var i Edge
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.Target,
			&i.Kind,
			&i.Volume,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodes = `-- name: ListNodes :many
SELECT id, type, subtype, label, description, schedule FROM nodes ORDER BY id
`

func (q *Queries) ListNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.Query(ctx, listNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Subtype,
			&i.Label,
			&i.Description,
			&i.Schedule,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEdge = `-- name: UpdateEdge :one
UPDATE edges
SET
    source = $1,
    target = $2,
    kind = $3,
    volume = $4
WHERE id = $5
RETURNING id, source, target, kind, volume
`

type UpdateEdgeParams struct {
	Source string `json:"source"`
	Target string `json:"target"`
	Kind   string `json:"kind"`
	Volume int32  `json:"volume"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateEdge(ctx context.Context, arg UpdateEdgeParams) (Edge, error) {
	row := q.db.QueryRow(ctx, updateEdge,
		arg.Source,
		arg.Target,
		arg.Kind,
		arg.Volume,
		arg.ID,
	)
	var i Edge
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.Target,
		&i.Kind,
		&i.Volume,
	)
	return i, err
}

const updateNode = `-- name: UpdateNode :one
UPDATE nodes
SET
    type = $1,
    subtype = $2,
    label = $3,
    description = $4,
    schedule = $5
WHERE id = $6
RETURNING id, type, subtype, label, description, schedule
`

type UpdateNodeParams struct {
	Type        string  `json:"type"`
	Subtype     *string `json:"subtype"`
	Label       string  `json:"label"`
	Description *string `json:"description"`
	Schedule    *string `json:"schedule"`
	ID          string  `json:"id"`
}

func (q *Queries) UpdateNode(ctx context.Context, arg UpdateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, updateNode,
		arg.Type,
		arg.Subtype,
		arg.Label,
		arg.Description,
		arg.Schedule,
		arg.ID,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Subtype,
		&i.Label,
		&i.Description,
		&i.Schedule,
	)
	return i, err
}
