// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateEdge(ctx context.Context, arg CreateEdgeParams) (MindmapEdge, error)
	CreateNode(ctx context.Context, arg CreateNodeParams) (MindmapNode, error)
	DeleteEdge(ctx context.Context, id string) error
	DeleteNode(ctx context.Context, id string) error
	GetEdge(ctx context.Context, id string) (MindmapEdge, error)
	GetNode(ctx context.Context, id string) (MindmapNode, error)
	ListEdges(ctx context.Context) ([]MindmapEdge, error)
	ListNodes(ctx context.Context) ([]MindmapNode, error)
	UpdateEdge(ctx context.Context, arg UpdateEdgeParams) (MindmapEdge, error)
	UpdateNode(ctx context.Context, arg UpdateNodeParams) (MindmapNode, error)
}

var _ Querier = (*Queries)(nil)
